services:
  node-playground:
    container_name: node-playground
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - main_network

networks:
    main_network:
        driver: bridge
